title: ASAOKA Homepage
description: アサオカのホームページ
author: アサオカ
copyrightHolder: ASAOKA
email: asaoka.biz@gmail.com
social:
  github: https://github.com/TakuyaAsaoka
  twitter: ""
  youtube: ""
noteRssUrl: https://note.com/limber_iguana638/rss
